### ISSUE TITLE
Fix blogs for mobile

### ISSUE THREAD

**Issue by Technickel-Dev** [Technickel-Dev/Technickel-Dev.github.io#9]
Something weird is going on with the code blocks and mobile responsivity in blogs. Something to do with the pre tag but will need some investigation

**Comment by magnetomax** [comment]
Findings: Its the custom max-width to .prose class in layout. Changing this is resolving issue for mobile but again reduces the width for desktop resolution. I am not sure if that is actual issue here.

**Comment by Technickel-Dev** [comment]
I'm a little late getting back to you but good find! To make things easier (and handle a lot of extra features) I've moved the blog portion of things over to Jekyll which should fix things
